[platform]
platform-svc ansible_host=192.168.122.130

[k3s_nodes]
k3s-1 ansible_host=192.168.122.131 k3s_init_node=true

[all:children]
platform
k3s_nodes

[all:vars]
ansible_user=debian
ansible_ssh_private_key_file=~/.ssh/homelab
timezone=Europe/Rome

[platform:vars]
opensearch_admin_password=Homelab@2025
opensearch_version=2.17.1
opensearch_dashboards_version=2.17.1
vault_version=1.18.3
compose_dir=/opt/homelab

[k3s_nodes:vars]
k3s_version=v1.32.3+k3s1
kube_vip_version=v0.8.9
kube_vip_ip=192.168.122.139
k3s_network_interface=eth0
k3s_api_server_url=https://192.168.122.139:6443
k3s_init_node_ip=192.168.122.131
