# Requisiti password OpenSearch >= 2.12: min 8 char, maiuscola, minuscola, numero, simbolo.
# Esempio valido: Homelab@2025
# Quando vorrai cifrare questa variabile in futuro:
#   ansible-vault encrypt_string 'LatuaPassword' --name 'opensearch_admin_password'
opensearch_admin_password: "Homelab@2025"

opensearch_version: "2.17.1"
opensearch_dashboards_version: "2.17.1"
vault_version: "1.18.3"

compose_dir: /opt/homelab
