---
# Eseguito su k3s-2 e k3s-3.
# Si collegano al VIP (192.168.122.139) che a questo punto è già attivo su k3s-1.
# --tls-san: anche i nodi che fanno join devono avere il VIP nel certificato.
# --disable traefik: coerente con il nodo init.

- name: Attendi che il VIP kube-vip sia raggiungibile dalla rete
  ansible.builtin.wait_for:
    host: "{{ kube_vip_ip }}"
    port: 6443
    timeout: 120
    delay: 5

- name: Scarica e installa k3s (nodo che si unisce al cluster)
  ansible.builtin.shell: >
    curl -sfL https://get.k3s.io |
    INSTALL_K3S_VERSION="{{ k3s_version }}"
    K3S_TOKEN="{{ hostvars['k3s-1']['k3s_node_token'] }}"
    sh -s - server
    --server https://{{ k3s_init_node_ip }}:6443
    --tls-san {{ kube_vip_ip }}
    --disable traefik
  args:
    creates: /usr/local/bin/k3s

- name: Attendi che il nodo sia Ready nel cluster
  ansible.builtin.command: >
    k3s kubectl get node {{ inventory_hostname }} -o jsonpath='{.status.conditions[-1].type}'
  register: node_status
  until: node_status.stdout == "Ready"
  retries: 20
  delay: 15
  changed_when: false
