services:

  opensearch:
    image: docker.io/opensearchproject/opensearch:${OPENSEARCH_VERSION}
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - plugins.security.ssl.http.enabled=true
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

  opensearch-dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards:${OPENSEARCH_DASHBOARDS_VERSION}
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    restart: unless-stopped

  vault:
    image: docker.io/hashicorp/vault:${VAULT_VERSION}
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
    ports:
      - "8200:8200"
    command: vault server -config=/vault/config/vault.hcl
    restart: unless-stopped

volumes:
  opensearch_data:
